//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAssociado.SMensalidade {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EMensalidade", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EMensalidade : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Identficador_MensalidadeField;
        
        private int ID_AssociadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WAssociado.SMensalidade.EAssociado AssociadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenciaField;
        
        private System.DateTime DataVencimentoField;
        
        private System.DateTime DataPagamentoField;
        
        private decimal ValorMensalidadeField;
        
        private decimal ValorPagamentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Identficador_Mensalidade {
            get {
                return this.Identficador_MensalidadeField;
            }
            set {
                if ((this.Identficador_MensalidadeField.Equals(value) != true)) {
                    this.Identficador_MensalidadeField = value;
                    this.RaisePropertyChanged("Identficador_Mensalidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ID_Associado {
            get {
                return this.ID_AssociadoField;
            }
            set {
                if ((this.ID_AssociadoField.Equals(value) != true)) {
                    this.ID_AssociadoField = value;
                    this.RaisePropertyChanged("ID_Associado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public WAssociado.SMensalidade.EAssociado Associado {
            get {
                return this.AssociadoField;
            }
            set {
                if ((object.ReferenceEquals(this.AssociadoField, value) != true)) {
                    this.AssociadoField = value;
                    this.RaisePropertyChanged("Associado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Referencia {
            get {
                return this.ReferenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenciaField, value) != true)) {
                    this.ReferenciaField = value;
                    this.RaisePropertyChanged("Referencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime DataVencimento {
            get {
                return this.DataVencimentoField;
            }
            set {
                if ((this.DataVencimentoField.Equals(value) != true)) {
                    this.DataVencimentoField = value;
                    this.RaisePropertyChanged("DataVencimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime DataPagamento {
            get {
                return this.DataPagamentoField;
            }
            set {
                if ((this.DataPagamentoField.Equals(value) != true)) {
                    this.DataPagamentoField = value;
                    this.RaisePropertyChanged("DataPagamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal ValorMensalidade {
            get {
                return this.ValorMensalidadeField;
            }
            set {
                if ((this.ValorMensalidadeField.Equals(value) != true)) {
                    this.ValorMensalidadeField = value;
                    this.RaisePropertyChanged("ValorMensalidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal ValorPagamento {
            get {
                return this.ValorPagamentoField;
            }
            set {
                if ((this.ValorPagamentoField.Equals(value) != true)) {
                    this.ValorPagamentoField = value;
                    this.RaisePropertyChanged("ValorPagamento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EAssociado", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EAssociado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int identificadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string enderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WAssociado.SMensalidade.ETipoAssociado tipoAssociadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int identificador {
            get {
                return this.identificadorField;
            }
            set {
                if ((this.identificadorField.Equals(value) != true)) {
                    this.identificadorField = value;
                    this.RaisePropertyChanged("identificador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string endereco {
            get {
                return this.enderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.enderecoField, value) != true)) {
                    this.enderecoField = value;
                    this.RaisePropertyChanged("endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string telefone {
            get {
                return this.telefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.telefoneField, value) != true)) {
                    this.telefoneField = value;
                    this.RaisePropertyChanged("telefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public WAssociado.SMensalidade.ETipoAssociado tipoAssociado {
            get {
                return this.tipoAssociadoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoAssociadoField, value) != true)) {
                    this.tipoAssociadoField = value;
                    this.RaisePropertyChanged("tipoAssociado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETipoAssociado", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ETipoAssociado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int identificadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descricaoField;
        
        private decimal valorMensalidadeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int identificador {
            get {
                return this.identificadorField;
            }
            set {
                if ((this.identificadorField.Equals(value) != true)) {
                    this.identificadorField = value;
                    this.RaisePropertyChanged("identificador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.descricaoField, value) != true)) {
                    this.descricaoField = value;
                    this.RaisePropertyChanged("descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal valorMensalidade {
            get {
                return this.valorMensalidadeField;
            }
            set {
                if ((this.valorMensalidadeField.Equals(value) != true)) {
                    this.valorMensalidadeField = value;
                    this.RaisePropertyChanged("valorMensalidade");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMensalidade.SMensalidadeSoap")]
    public interface SMensalidadeSoap {
        
        // CODEGEN: Generating message contract since element name eMensalidade from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Incluir", ReplyAction="*")]
        WAssociado.SMensalidade.IncluirResponse Incluir(WAssociado.SMensalidade.IncluirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Incluir", ReplyAction="*")]
        System.IAsyncResult BeginIncluir(WAssociado.SMensalidade.IncluirRequest request, System.AsyncCallback callback, object asyncState);
        
        WAssociado.SMensalidade.IncluirResponse EndIncluir(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name eMensalidade from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Alterar", ReplyAction="*")]
        WAssociado.SMensalidade.AlterarResponse Alterar(WAssociado.SMensalidade.AlterarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Alterar", ReplyAction="*")]
        System.IAsyncResult BeginAlterar(WAssociado.SMensalidade.AlterarRequest request, System.AsyncCallback callback, object asyncState);
        
        WAssociado.SMensalidade.AlterarResponse EndAlterar(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Excluir", ReplyAction="*")]
        bool Excluir(int codigoMensalidade);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Excluir", ReplyAction="*")]
        System.IAsyncResult BeginExcluir(int codigoMensalidade, System.AsyncCallback callback, object asyncState);
        
        bool EndExcluir(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name ConsultarResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consultar", ReplyAction="*")]
        WAssociado.SMensalidade.ConsultarResponse Consultar(WAssociado.SMensalidade.ConsultarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Consultar", ReplyAction="*")]
        System.IAsyncResult BeginConsultar(WAssociado.SMensalidade.ConsultarRequest request, System.AsyncCallback callback, object asyncState);
        
        WAssociado.SMensalidade.ConsultarResponse EndConsultar(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name ListarResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        WAssociado.SMensalidade.ListarResponse Listar(WAssociado.SMensalidade.ListarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.IAsyncResult BeginListar(WAssociado.SMensalidade.ListarRequest request, System.AsyncCallback callback, object asyncState);
        
        WAssociado.SMensalidade.ListarResponse EndListar(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IncluirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Incluir", Namespace="http://tempuri.org/", Order=0)]
        public WAssociado.SMensalidade.IncluirRequestBody Body;
        
        public IncluirRequest() {
        }
        
        public IncluirRequest(WAssociado.SMensalidade.IncluirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IncluirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WAssociado.SMensalidade.EMensalidade eMensalidade;
        
        public IncluirRequestBody() {
        }
        
        public IncluirRequestBody(WAssociado.SMensalidade.EMensalidade eMensalidade) {
            this.eMensalidade = eMensalidade;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IncluirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IncluirResponse", Namespace="http://tempuri.org/", Order=0)]
        public WAssociado.SMensalidade.IncluirResponseBody Body;
        
        public IncluirResponse() {
        }
        
        public IncluirResponse(WAssociado.SMensalidade.IncluirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IncluirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WAssociado.SMensalidade.EMensalidade IncluirResult;
        
        public IncluirResponseBody() {
        }
        
        public IncluirResponseBody(WAssociado.SMensalidade.EMensalidade IncluirResult) {
            this.IncluirResult = IncluirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AlterarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Alterar", Namespace="http://tempuri.org/", Order=0)]
        public WAssociado.SMensalidade.AlterarRequestBody Body;
        
        public AlterarRequest() {
        }
        
        public AlterarRequest(WAssociado.SMensalidade.AlterarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AlterarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WAssociado.SMensalidade.EMensalidade eMensalidade;
        
        public AlterarRequestBody() {
        }
        
        public AlterarRequestBody(WAssociado.SMensalidade.EMensalidade eMensalidade) {
            this.eMensalidade = eMensalidade;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AlterarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AlterarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WAssociado.SMensalidade.AlterarResponseBody Body;
        
        public AlterarResponse() {
        }
        
        public AlterarResponse(WAssociado.SMensalidade.AlterarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AlterarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AlterarResult;
        
        public AlterarResponseBody() {
        }
        
        public AlterarResponseBody(bool AlterarResult) {
            this.AlterarResult = AlterarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consultar", Namespace="http://tempuri.org/", Order=0)]
        public WAssociado.SMensalidade.ConsultarRequestBody Body;
        
        public ConsultarRequest() {
        }
        
        public ConsultarRequest(WAssociado.SMensalidade.ConsultarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codigoMensalidade;
        
        public ConsultarRequestBody() {
        }
        
        public ConsultarRequestBody(int codigoMensalidade) {
            this.codigoMensalidade = codigoMensalidade;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WAssociado.SMensalidade.ConsultarResponseBody Body;
        
        public ConsultarResponse() {
        }
        
        public ConsultarResponse(WAssociado.SMensalidade.ConsultarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WAssociado.SMensalidade.EMensalidade ConsultarResult;
        
        public ConsultarResponseBody() {
        }
        
        public ConsultarResponseBody(WAssociado.SMensalidade.EMensalidade ConsultarResult) {
            this.ConsultarResult = ConsultarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Listar", Namespace="http://tempuri.org/", Order=0)]
        public WAssociado.SMensalidade.ListarRequestBody Body;
        
        public ListarRequest() {
        }
        
        public ListarRequest(WAssociado.SMensalidade.ListarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codigoAssociado;
        
        public ListarRequestBody() {
        }
        
        public ListarRequestBody(int codigoAssociado) {
            this.codigoAssociado = codigoAssociado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WAssociado.SMensalidade.ListarResponseBody Body;
        
        public ListarResponse() {
        }
        
        public ListarResponse(WAssociado.SMensalidade.ListarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WAssociado.SMensalidade.EMensalidade[] ListarResult;
        
        public ListarResponseBody() {
        }
        
        public ListarResponseBody(WAssociado.SMensalidade.EMensalidade[] ListarResult) {
            this.ListarResult = ListarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMensalidadeSoapChannel : WAssociado.SMensalidade.SMensalidadeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IncluirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public IncluirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WAssociado.SMensalidade.EMensalidade Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WAssociado.SMensalidade.EMensalidade)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlterarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AlterarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExcluirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ExcluirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WAssociado.SMensalidade.EMensalidade Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WAssociado.SMensalidade.EMensalidade)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WAssociado.SMensalidade.EMensalidade[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WAssociado.SMensalidade.EMensalidade[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMensalidadeSoapClient : System.ServiceModel.ClientBase<WAssociado.SMensalidade.SMensalidadeSoap>, WAssociado.SMensalidade.SMensalidadeSoap {
        
        private BeginOperationDelegate onBeginIncluirDelegate;
        
        private EndOperationDelegate onEndIncluirDelegate;
        
        private System.Threading.SendOrPostCallback onIncluirCompletedDelegate;
        
        private BeginOperationDelegate onBeginAlterarDelegate;
        
        private EndOperationDelegate onEndAlterarDelegate;
        
        private System.Threading.SendOrPostCallback onAlterarCompletedDelegate;
        
        private BeginOperationDelegate onBeginExcluirDelegate;
        
        private EndOperationDelegate onEndExcluirDelegate;
        
        private System.Threading.SendOrPostCallback onExcluirCompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultarDelegate;
        
        private EndOperationDelegate onEndConsultarDelegate;
        
        private System.Threading.SendOrPostCallback onConsultarCompletedDelegate;
        
        private BeginOperationDelegate onBeginListarDelegate;
        
        private EndOperationDelegate onEndListarDelegate;
        
        private System.Threading.SendOrPostCallback onListarCompletedDelegate;
        
        public SMensalidadeSoapClient() {
        }
        
        public SMensalidadeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMensalidadeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMensalidadeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMensalidadeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<IncluirCompletedEventArgs> IncluirCompleted;
        
        public event System.EventHandler<AlterarCompletedEventArgs> AlterarCompleted;
        
        public event System.EventHandler<ExcluirCompletedEventArgs> ExcluirCompleted;
        
        public event System.EventHandler<ConsultarCompletedEventArgs> ConsultarCompleted;
        
        public event System.EventHandler<ListarCompletedEventArgs> ListarCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAssociado.SMensalidade.IncluirResponse WAssociado.SMensalidade.SMensalidadeSoap.Incluir(WAssociado.SMensalidade.IncluirRequest request) {
            return base.Channel.Incluir(request);
        }
        
        public WAssociado.SMensalidade.EMensalidade Incluir(WAssociado.SMensalidade.EMensalidade eMensalidade) {
            WAssociado.SMensalidade.IncluirRequest inValue = new WAssociado.SMensalidade.IncluirRequest();
            inValue.Body = new WAssociado.SMensalidade.IncluirRequestBody();
            inValue.Body.eMensalidade = eMensalidade;
            WAssociado.SMensalidade.IncluirResponse retVal = ((WAssociado.SMensalidade.SMensalidadeSoap)(this)).Incluir(inValue);
            return retVal.Body.IncluirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WAssociado.SMensalidade.SMensalidadeSoap.BeginIncluir(WAssociado.SMensalidade.IncluirRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginIncluir(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginIncluir(WAssociado.SMensalidade.EMensalidade eMensalidade, System.AsyncCallback callback, object asyncState) {
            WAssociado.SMensalidade.IncluirRequest inValue = new WAssociado.SMensalidade.IncluirRequest();
            inValue.Body = new WAssociado.SMensalidade.IncluirRequestBody();
            inValue.Body.eMensalidade = eMensalidade;
            return ((WAssociado.SMensalidade.SMensalidadeSoap)(this)).BeginIncluir(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAssociado.SMensalidade.IncluirResponse WAssociado.SMensalidade.SMensalidadeSoap.EndIncluir(System.IAsyncResult result) {
            return base.Channel.EndIncluir(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WAssociado.SMensalidade.EMensalidade EndIncluir(System.IAsyncResult result) {
            WAssociado.SMensalidade.IncluirResponse retVal = ((WAssociado.SMensalidade.SMensalidadeSoap)(this)).EndIncluir(result);
            return retVal.Body.IncluirResult;
        }
        
        private System.IAsyncResult OnBeginIncluir(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WAssociado.SMensalidade.EMensalidade eMensalidade = ((WAssociado.SMensalidade.EMensalidade)(inValues[0]));
            return this.BeginIncluir(eMensalidade, callback, asyncState);
        }
        
        private object[] OnEndIncluir(System.IAsyncResult result) {
            WAssociado.SMensalidade.EMensalidade retVal = this.EndIncluir(result);
            return new object[] {
                    retVal};
        }
        
        private void OnIncluirCompleted(object state) {
            if ((this.IncluirCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.IncluirCompleted(this, new IncluirCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void IncluirAsync(WAssociado.SMensalidade.EMensalidade eMensalidade) {
            this.IncluirAsync(eMensalidade, null);
        }
        
        public void IncluirAsync(WAssociado.SMensalidade.EMensalidade eMensalidade, object userState) {
            if ((this.onBeginIncluirDelegate == null)) {
                this.onBeginIncluirDelegate = new BeginOperationDelegate(this.OnBeginIncluir);
            }
            if ((this.onEndIncluirDelegate == null)) {
                this.onEndIncluirDelegate = new EndOperationDelegate(this.OnEndIncluir);
            }
            if ((this.onIncluirCompletedDelegate == null)) {
                this.onIncluirCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnIncluirCompleted);
            }
            base.InvokeAsync(this.onBeginIncluirDelegate, new object[] {
                        eMensalidade}, this.onEndIncluirDelegate, this.onIncluirCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAssociado.SMensalidade.AlterarResponse WAssociado.SMensalidade.SMensalidadeSoap.Alterar(WAssociado.SMensalidade.AlterarRequest request) {
            return base.Channel.Alterar(request);
        }
        
        public bool Alterar(WAssociado.SMensalidade.EMensalidade eMensalidade) {
            WAssociado.SMensalidade.AlterarRequest inValue = new WAssociado.SMensalidade.AlterarRequest();
            inValue.Body = new WAssociado.SMensalidade.AlterarRequestBody();
            inValue.Body.eMensalidade = eMensalidade;
            WAssociado.SMensalidade.AlterarResponse retVal = ((WAssociado.SMensalidade.SMensalidadeSoap)(this)).Alterar(inValue);
            return retVal.Body.AlterarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WAssociado.SMensalidade.SMensalidadeSoap.BeginAlterar(WAssociado.SMensalidade.AlterarRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAlterar(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAlterar(WAssociado.SMensalidade.EMensalidade eMensalidade, System.AsyncCallback callback, object asyncState) {
            WAssociado.SMensalidade.AlterarRequest inValue = new WAssociado.SMensalidade.AlterarRequest();
            inValue.Body = new WAssociado.SMensalidade.AlterarRequestBody();
            inValue.Body.eMensalidade = eMensalidade;
            return ((WAssociado.SMensalidade.SMensalidadeSoap)(this)).BeginAlterar(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAssociado.SMensalidade.AlterarResponse WAssociado.SMensalidade.SMensalidadeSoap.EndAlterar(System.IAsyncResult result) {
            return base.Channel.EndAlterar(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndAlterar(System.IAsyncResult result) {
            WAssociado.SMensalidade.AlterarResponse retVal = ((WAssociado.SMensalidade.SMensalidadeSoap)(this)).EndAlterar(result);
            return retVal.Body.AlterarResult;
        }
        
        private System.IAsyncResult OnBeginAlterar(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WAssociado.SMensalidade.EMensalidade eMensalidade = ((WAssociado.SMensalidade.EMensalidade)(inValues[0]));
            return this.BeginAlterar(eMensalidade, callback, asyncState);
        }
        
        private object[] OnEndAlterar(System.IAsyncResult result) {
            bool retVal = this.EndAlterar(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAlterarCompleted(object state) {
            if ((this.AlterarCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AlterarCompleted(this, new AlterarCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AlterarAsync(WAssociado.SMensalidade.EMensalidade eMensalidade) {
            this.AlterarAsync(eMensalidade, null);
        }
        
        public void AlterarAsync(WAssociado.SMensalidade.EMensalidade eMensalidade, object userState) {
            if ((this.onBeginAlterarDelegate == null)) {
                this.onBeginAlterarDelegate = new BeginOperationDelegate(this.OnBeginAlterar);
            }
            if ((this.onEndAlterarDelegate == null)) {
                this.onEndAlterarDelegate = new EndOperationDelegate(this.OnEndAlterar);
            }
            if ((this.onAlterarCompletedDelegate == null)) {
                this.onAlterarCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAlterarCompleted);
            }
            base.InvokeAsync(this.onBeginAlterarDelegate, new object[] {
                        eMensalidade}, this.onEndAlterarDelegate, this.onAlterarCompletedDelegate, userState);
        }
        
        public bool Excluir(int codigoMensalidade) {
            return base.Channel.Excluir(codigoMensalidade);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginExcluir(int codigoMensalidade, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginExcluir(codigoMensalidade, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndExcluir(System.IAsyncResult result) {
            return base.Channel.EndExcluir(result);
        }
        
        private System.IAsyncResult OnBeginExcluir(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int codigoMensalidade = ((int)(inValues[0]));
            return this.BeginExcluir(codigoMensalidade, callback, asyncState);
        }
        
        private object[] OnEndExcluir(System.IAsyncResult result) {
            bool retVal = this.EndExcluir(result);
            return new object[] {
                    retVal};
        }
        
        private void OnExcluirCompleted(object state) {
            if ((this.ExcluirCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ExcluirCompleted(this, new ExcluirCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ExcluirAsync(int codigoMensalidade) {
            this.ExcluirAsync(codigoMensalidade, null);
        }
        
        public void ExcluirAsync(int codigoMensalidade, object userState) {
            if ((this.onBeginExcluirDelegate == null)) {
                this.onBeginExcluirDelegate = new BeginOperationDelegate(this.OnBeginExcluir);
            }
            if ((this.onEndExcluirDelegate == null)) {
                this.onEndExcluirDelegate = new EndOperationDelegate(this.OnEndExcluir);
            }
            if ((this.onExcluirCompletedDelegate == null)) {
                this.onExcluirCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnExcluirCompleted);
            }
            base.InvokeAsync(this.onBeginExcluirDelegate, new object[] {
                        codigoMensalidade}, this.onEndExcluirDelegate, this.onExcluirCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAssociado.SMensalidade.ConsultarResponse WAssociado.SMensalidade.SMensalidadeSoap.Consultar(WAssociado.SMensalidade.ConsultarRequest request) {
            return base.Channel.Consultar(request);
        }
        
        public WAssociado.SMensalidade.EMensalidade Consultar(int codigoMensalidade) {
            WAssociado.SMensalidade.ConsultarRequest inValue = new WAssociado.SMensalidade.ConsultarRequest();
            inValue.Body = new WAssociado.SMensalidade.ConsultarRequestBody();
            inValue.Body.codigoMensalidade = codigoMensalidade;
            WAssociado.SMensalidade.ConsultarResponse retVal = ((WAssociado.SMensalidade.SMensalidadeSoap)(this)).Consultar(inValue);
            return retVal.Body.ConsultarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WAssociado.SMensalidade.SMensalidadeSoap.BeginConsultar(WAssociado.SMensalidade.ConsultarRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultar(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginConsultar(int codigoMensalidade, System.AsyncCallback callback, object asyncState) {
            WAssociado.SMensalidade.ConsultarRequest inValue = new WAssociado.SMensalidade.ConsultarRequest();
            inValue.Body = new WAssociado.SMensalidade.ConsultarRequestBody();
            inValue.Body.codigoMensalidade = codigoMensalidade;
            return ((WAssociado.SMensalidade.SMensalidadeSoap)(this)).BeginConsultar(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAssociado.SMensalidade.ConsultarResponse WAssociado.SMensalidade.SMensalidadeSoap.EndConsultar(System.IAsyncResult result) {
            return base.Channel.EndConsultar(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WAssociado.SMensalidade.EMensalidade EndConsultar(System.IAsyncResult result) {
            WAssociado.SMensalidade.ConsultarResponse retVal = ((WAssociado.SMensalidade.SMensalidadeSoap)(this)).EndConsultar(result);
            return retVal.Body.ConsultarResult;
        }
        
        private System.IAsyncResult OnBeginConsultar(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int codigoMensalidade = ((int)(inValues[0]));
            return this.BeginConsultar(codigoMensalidade, callback, asyncState);
        }
        
        private object[] OnEndConsultar(System.IAsyncResult result) {
            WAssociado.SMensalidade.EMensalidade retVal = this.EndConsultar(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultarCompleted(object state) {
            if ((this.ConsultarCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultarCompleted(this, new ConsultarCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultarAsync(int codigoMensalidade) {
            this.ConsultarAsync(codigoMensalidade, null);
        }
        
        public void ConsultarAsync(int codigoMensalidade, object userState) {
            if ((this.onBeginConsultarDelegate == null)) {
                this.onBeginConsultarDelegate = new BeginOperationDelegate(this.OnBeginConsultar);
            }
            if ((this.onEndConsultarDelegate == null)) {
                this.onEndConsultarDelegate = new EndOperationDelegate(this.OnEndConsultar);
            }
            if ((this.onConsultarCompletedDelegate == null)) {
                this.onConsultarCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultarCompleted);
            }
            base.InvokeAsync(this.onBeginConsultarDelegate, new object[] {
                        codigoMensalidade}, this.onEndConsultarDelegate, this.onConsultarCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAssociado.SMensalidade.ListarResponse WAssociado.SMensalidade.SMensalidadeSoap.Listar(WAssociado.SMensalidade.ListarRequest request) {
            return base.Channel.Listar(request);
        }
        
        public WAssociado.SMensalidade.EMensalidade[] Listar(int codigoAssociado) {
            WAssociado.SMensalidade.ListarRequest inValue = new WAssociado.SMensalidade.ListarRequest();
            inValue.Body = new WAssociado.SMensalidade.ListarRequestBody();
            inValue.Body.codigoAssociado = codigoAssociado;
            WAssociado.SMensalidade.ListarResponse retVal = ((WAssociado.SMensalidade.SMensalidadeSoap)(this)).Listar(inValue);
            return retVal.Body.ListarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WAssociado.SMensalidade.SMensalidadeSoap.BeginListar(WAssociado.SMensalidade.ListarRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListar(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginListar(int codigoAssociado, System.AsyncCallback callback, object asyncState) {
            WAssociado.SMensalidade.ListarRequest inValue = new WAssociado.SMensalidade.ListarRequest();
            inValue.Body = new WAssociado.SMensalidade.ListarRequestBody();
            inValue.Body.codigoAssociado = codigoAssociado;
            return ((WAssociado.SMensalidade.SMensalidadeSoap)(this)).BeginListar(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAssociado.SMensalidade.ListarResponse WAssociado.SMensalidade.SMensalidadeSoap.EndListar(System.IAsyncResult result) {
            return base.Channel.EndListar(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WAssociado.SMensalidade.EMensalidade[] EndListar(System.IAsyncResult result) {
            WAssociado.SMensalidade.ListarResponse retVal = ((WAssociado.SMensalidade.SMensalidadeSoap)(this)).EndListar(result);
            return retVal.Body.ListarResult;
        }
        
        private System.IAsyncResult OnBeginListar(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int codigoAssociado = ((int)(inValues[0]));
            return this.BeginListar(codigoAssociado, callback, asyncState);
        }
        
        private object[] OnEndListar(System.IAsyncResult result) {
            WAssociado.SMensalidade.EMensalidade[] retVal = this.EndListar(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListarCompleted(object state) {
            if ((this.ListarCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListarCompleted(this, new ListarCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListarAsync(int codigoAssociado) {
            this.ListarAsync(codigoAssociado, null);
        }
        
        public void ListarAsync(int codigoAssociado, object userState) {
            if ((this.onBeginListarDelegate == null)) {
                this.onBeginListarDelegate = new BeginOperationDelegate(this.OnBeginListar);
            }
            if ((this.onEndListarDelegate == null)) {
                this.onEndListarDelegate = new EndOperationDelegate(this.OnEndListar);
            }
            if ((this.onListarCompletedDelegate == null)) {
                this.onListarCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListarCompleted);
            }
            base.InvokeAsync(this.onBeginListarDelegate, new object[] {
                        codigoAssociado}, this.onEndListarDelegate, this.onListarCompletedDelegate, userState);
        }
    }
}
