//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAssociado.SAssociado {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EAssociado", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EAssociado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int identificadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string enderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WAssociado.SAssociado.ETipoAssociado tipoAssociadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int identificador {
            get {
                return this.identificadorField;
            }
            set {
                if ((this.identificadorField.Equals(value) != true)) {
                    this.identificadorField = value;
                    this.RaisePropertyChanged("identificador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string endereco {
            get {
                return this.enderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.enderecoField, value) != true)) {
                    this.enderecoField = value;
                    this.RaisePropertyChanged("endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string telefone {
            get {
                return this.telefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.telefoneField, value) != true)) {
                    this.telefoneField = value;
                    this.RaisePropertyChanged("telefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public WAssociado.SAssociado.ETipoAssociado tipoAssociado {
            get {
                return this.tipoAssociadoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoAssociadoField, value) != true)) {
                    this.tipoAssociadoField = value;
                    this.RaisePropertyChanged("tipoAssociado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETipoAssociado", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ETipoAssociado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int identificadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descricaoField;
        
        private decimal valorMensalidadeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int identificador {
            get {
                return this.identificadorField;
            }
            set {
                if ((this.identificadorField.Equals(value) != true)) {
                    this.identificadorField = value;
                    this.RaisePropertyChanged("identificador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.descricaoField, value) != true)) {
                    this.descricaoField = value;
                    this.RaisePropertyChanged("descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal valorMensalidade {
            get {
                return this.valorMensalidadeField;
            }
            set {
                if ((this.valorMensalidadeField.Equals(value) != true)) {
                    this.valorMensalidadeField = value;
                    this.RaisePropertyChanged("valorMensalidade");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SAssociado.SAssociadoSoap")]
    public interface SAssociadoSoap {
        
        // CODEGEN: Generating message contract since element name ConsultarResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consultar", ReplyAction="*")]
        WAssociado.SAssociado.ConsultarResponse Consultar(WAssociado.SAssociado.ConsultarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Consultar", ReplyAction="*")]
        System.IAsyncResult BeginConsultar(WAssociado.SAssociado.ConsultarRequest request, System.AsyncCallback callback, object asyncState);
        
        WAssociado.SAssociado.ConsultarResponse EndConsultar(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consultar", Namespace="http://tempuri.org/", Order=0)]
        public WAssociado.SAssociado.ConsultarRequestBody Body;
        
        public ConsultarRequest() {
        }
        
        public ConsultarRequest(WAssociado.SAssociado.ConsultarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idAssociado;
        
        public ConsultarRequestBody() {
        }
        
        public ConsultarRequestBody(int idAssociado) {
            this.idAssociado = idAssociado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WAssociado.SAssociado.ConsultarResponseBody Body;
        
        public ConsultarResponse() {
        }
        
        public ConsultarResponse(WAssociado.SAssociado.ConsultarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WAssociado.SAssociado.EAssociado ConsultarResult;
        
        public ConsultarResponseBody() {
        }
        
        public ConsultarResponseBody(WAssociado.SAssociado.EAssociado ConsultarResult) {
            this.ConsultarResult = ConsultarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SAssociadoSoapChannel : WAssociado.SAssociado.SAssociadoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WAssociado.SAssociado.EAssociado Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WAssociado.SAssociado.EAssociado)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SAssociadoSoapClient : System.ServiceModel.ClientBase<WAssociado.SAssociado.SAssociadoSoap>, WAssociado.SAssociado.SAssociadoSoap {
        
        private BeginOperationDelegate onBeginConsultarDelegate;
        
        private EndOperationDelegate onEndConsultarDelegate;
        
        private System.Threading.SendOrPostCallback onConsultarCompletedDelegate;
        
        public SAssociadoSoapClient() {
        }
        
        public SAssociadoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SAssociadoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAssociadoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAssociadoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ConsultarCompletedEventArgs> ConsultarCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAssociado.SAssociado.ConsultarResponse WAssociado.SAssociado.SAssociadoSoap.Consultar(WAssociado.SAssociado.ConsultarRequest request) {
            return base.Channel.Consultar(request);
        }
        
        public WAssociado.SAssociado.EAssociado Consultar(int idAssociado) {
            WAssociado.SAssociado.ConsultarRequest inValue = new WAssociado.SAssociado.ConsultarRequest();
            inValue.Body = new WAssociado.SAssociado.ConsultarRequestBody();
            inValue.Body.idAssociado = idAssociado;
            WAssociado.SAssociado.ConsultarResponse retVal = ((WAssociado.SAssociado.SAssociadoSoap)(this)).Consultar(inValue);
            return retVal.Body.ConsultarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WAssociado.SAssociado.SAssociadoSoap.BeginConsultar(WAssociado.SAssociado.ConsultarRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultar(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginConsultar(int idAssociado, System.AsyncCallback callback, object asyncState) {
            WAssociado.SAssociado.ConsultarRequest inValue = new WAssociado.SAssociado.ConsultarRequest();
            inValue.Body = new WAssociado.SAssociado.ConsultarRequestBody();
            inValue.Body.idAssociado = idAssociado;
            return ((WAssociado.SAssociado.SAssociadoSoap)(this)).BeginConsultar(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAssociado.SAssociado.ConsultarResponse WAssociado.SAssociado.SAssociadoSoap.EndConsultar(System.IAsyncResult result) {
            return base.Channel.EndConsultar(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WAssociado.SAssociado.EAssociado EndConsultar(System.IAsyncResult result) {
            WAssociado.SAssociado.ConsultarResponse retVal = ((WAssociado.SAssociado.SAssociadoSoap)(this)).EndConsultar(result);
            return retVal.Body.ConsultarResult;
        }
        
        private System.IAsyncResult OnBeginConsultar(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int idAssociado = ((int)(inValues[0]));
            return this.BeginConsultar(idAssociado, callback, asyncState);
        }
        
        private object[] OnEndConsultar(System.IAsyncResult result) {
            WAssociado.SAssociado.EAssociado retVal = this.EndConsultar(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultarCompleted(object state) {
            if ((this.ConsultarCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultarCompleted(this, new ConsultarCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultarAsync(int idAssociado) {
            this.ConsultarAsync(idAssociado, null);
        }
        
        public void ConsultarAsync(int idAssociado, object userState) {
            if ((this.onBeginConsultarDelegate == null)) {
                this.onBeginConsultarDelegate = new BeginOperationDelegate(this.OnBeginConsultar);
            }
            if ((this.onEndConsultarDelegate == null)) {
                this.onEndConsultarDelegate = new EndOperationDelegate(this.OnEndConsultar);
            }
            if ((this.onConsultarCompletedDelegate == null)) {
                this.onConsultarCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultarCompleted);
            }
            base.InvokeAsync(this.onBeginConsultarDelegate, new object[] {
                        idAssociado}, this.onEndConsultarDelegate, this.onConsultarCompletedDelegate, userState);
        }
    }
}
